---
name: Tests
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Check format
        run: make check-fmt
      - name: GolangCI-Lint
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
          $(go env GOPATH)/bin/golangci-lint --version
          $(go env GOPATH)/bin/golangci-lint run
      - name: Staticcheck
        run: |
          GO111MODULE=off go get -u honnef.co/go/tools/cmd/staticcheck
          $(go env GOPATH)/bin/staticcheck ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.14]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Run tests
        run: make test
      - name: Show test coverage
        run: make coverage
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: c.out
          outfile: c.lcov
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: c.lcov
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.14]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build
        run: make build